site_name: CiviCRM Committees
site_description: Extension to synchronise committee structures, such as parliaments, sessions, boards, etc
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.committees

theme:
  name: material

nav:
  - Introduction: index.md
  - Importer:
    - Kürschner List Importer: importer/kuerschner/index.md
  - Syncer:
    - Oxfam Bundestag Importer: syncer/oxfam/index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
